//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikaciji.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj katedru.
        /// </summary>
        public static string Add_department {
            get {
                return ResourceManager.GetString("Add department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj entitet.
        /// </summary>
        public static string Add_entity {
            get {
                return ResourceManager.GetString("Add entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje profesora.
        /// </summary>
        public static string Add_professor {
            get {
                return ResourceManager.GetString("Add professor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa stanovanja:.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje studenta.
        /// </summary>
        public static string AddStudent {
            get {
                return ResourceManager.GetString("AddStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje predmeta.
        /// </summary>
        public static string ADDSUBJECT {
            get {
                return ResourceManager.GetString("ADDSUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autori:.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosek:.
        /// </summary>
        public static string Average_grade {
            get {
                return ResourceManager.GetString("Average grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sef ID:.
        /// </summary>
        public static string Boss_id {
            get {
                return ResourceManager.GetString("Boss id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj ESPB:.
        /// </summary>
        public static string Broj_espb_ {
            get {
                return ResourceManager.GetString("Broj espb:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budžet.
        /// </summary>
        public static string Budzet {
            get {
                return ResourceManager.GetString("Budzet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvori.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifra:.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt telefon:.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra predmeta.
        /// </summary>
        public static string Course_code {
            get {
                return ResourceManager.GetString("Course code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv predmeta.
        /// </summary>
        public static string Course_name {
            get {
                return ResourceManager.GetString("Course name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predmeti.
        /// </summary>
        public static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rodjenja:.
        /// </summary>
        public static string Date_of_birth {
            get {
                return ResourceManager.GetString("Date of birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum*:.
        /// </summary>
        public static string Datum_ {
            get {
                return ResourceManager.GetString("Datum*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izbriši.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izbriši entitet.
        /// </summary>
        public static string Delete_entity {
            get {
                return ResourceManager.GetString("Delete entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID katedre:.
        /// </summary>
        public static string Department_ID {
            get {
                return ResourceManager.GetString("Department ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katedre.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj predmet.
        /// </summary>
        public static string Dodaj_predmet {
            get {
                return ResourceManager.GetString("Dodaj predmet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail adresa:.
        /// </summary>
        public static string E_mail_address {
            get {
                return ResourceManager.GetString("E-mail address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni predmet.
        /// </summary>
        public static string Edit_course {
            get {
                return ResourceManager.GetString("Edit course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni katedru.
        /// </summary>
        public static string Edit_department {
            get {
                return ResourceManager.GetString("Edit department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni entitet.
        /// </summary>
        public static string Edit_entity {
            get {
                return ResourceManager.GetString("Edit entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni profesora.
        /// </summary>
        public static string Edit_professor {
            get {
                return ResourceManager.GetString("Edit professor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESPB.
        /// </summary>
        public static string ESPB {
            get {
                return ResourceManager.GetString("ESPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fajl.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina slušanja:.
        /// </summary>
        public static string Godina_slusanja_ {
            get {
                return ResourceManager.GetString("Godina slusanja:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina upisa:.
        /// </summary>
        public static string Godina_upisa {
            get {
                return ResourceManager.GetString("Godina upisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina staža:.
        /// </summary>
        public static string Godine_staza {
            get {
                return ResourceManager.GetString("Godine staza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomoć.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I (prva).
        /// </summary>
        public static string I__prva_ {
            get {
                return ResourceManager.GetString("I (prva)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to II (druga).
        /// </summary>
        public static string II__druga_ {
            get {
                return ResourceManager.GetString("II (druga)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to III (treća).
        /// </summary>
        public static string III__treća_ {
            get {
                return ResourceManager.GetString("III (treća)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije.
        /// </summary>
        public static string Informacije {
            get {
                return ResourceManager.GetString("Informacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IV (četvrta).
        /// </summary>
        public static string IV__četvrta_ {
            get {
                return ResourceManager.GetString("IV (četvrta)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letnji.
        /// </summary>
        public static string Letnji {
            get {
                return ResourceManager.GetString("Letnji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj lične karte:.
        /// </summary>
        public static string Licna_karta {
            get {
                return ResourceManager.GetString("Licna karta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokalizacija.
        /// </summary>
        public static string Localization {
            get {
                return ResourceManager.GetString("Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Način finansiranja:.
        /// </summary>
        public static string Nacin_finansiranja {
            get {
                return ResourceManager.GetString("Nacin finansiranja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime:.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv:.
        /// </summary>
        public static string NameNaz {
            get {
                return ResourceManager.GetString("NameNaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv predmeta*:.
        /// </summary>
        public static string Naziv_ {
            get {
                return ResourceManager.GetString("Naziv*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepoloženi premeti.
        /// </summary>
        public static string Nepolozeni {
            get {
                return ResourceManager.GetString("Nepolozeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj ESPB poena:.
        /// </summary>
        public static string Number_of_ESPB_points {
            get {
                return ResourceManager.GetString("Number of ESPB points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena.
        /// </summary>
        public static string Ocena {
            get {
                return ResourceManager.GetString("Ocena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena*:.
        /// </summary>
        public static string Ocena_ {
            get {
                return ResourceManager.GetString("Ocena*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi profesora.
        /// </summary>
        public static string Odaberi_profesora {
            get {
                return ResourceManager.GetString("Odaberi profesora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otvori.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Položeni predmeti.
        /// </summary>
        public static string Polozeni {
            get {
                return ResourceManager.GetString("Polozeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poništi ocenu.
        /// </summary>
        public static string Ponisti_ocenu {
            get {
                return ResourceManager.GetString("Ponisti ocenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavi za šefa.
        /// </summary>
        public static string Postavi_za_sefa {
            get {
                return ResourceManager.GetString("Postavi za sefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predmeti.
        /// </summary>
        public static string Predmeti {
            get {
                return ResourceManager.GetString("Predmeti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži predmete za katedru.
        /// </summary>
        public static string Prikazi_predmete_za_katedru {
            get {
                return ResourceManager.GetString("Prikazi predmete za katedru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži profesore.
        /// </summary>
        public static string Prikazi_profesore {
            get {
                return ResourceManager.GetString("Prikazi profesore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesori koji predaju izabranom studentu:.
        /// </summary>
        public static string Profesori_koji_predaju_izabranom_studentu_ {
            get {
                return ResourceManager.GetString("Profesori koji predaju izabranom studentu:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesori na katedri:.
        /// </summary>
        public static string Profesori_na_katedri {
            get {
                return ResourceManager.GetString("Profesori na katedri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID profesora:.
        /// </summary>
        public static string Professor_ID {
            get {
                return ResourceManager.GetString("Professor ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesori.
        /// </summary>
        public static string Professors {
            get {
                return ResourceManager.GetString("Professors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukloni.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2023 Studentska služba. Sva prava zadržana..
        /// </summary>
        public static string Rights {
            get {
                return ResourceManager.GetString("Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samofinansirajući.
        /// </summary>
        public static string Samofinansirajuci {
            get {
                return ResourceManager.GetString("Samofinansirajuci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraži.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestar:.
        /// </summary>
        public static string Semester {
            get {
                return ResourceManager.GetString("Semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string Semicolon {
            get {
                return ResourceManager.GetString("Semicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski.
        /// </summary>
        public static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži entitet.
        /// </summary>
        public static string Show_entity {
            get {
                return ResourceManager.GetString("Show entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži profesore za katedru.
        /// </summary>
        public static string Show_professors_for_department {
            get {
                return ResourceManager.GetString("Show professors for department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži profesore izabranog studenta.
        /// </summary>
        public static string ShowProf {
            get {
                return ResourceManager.GetString("ShowProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži sve studente kojima predaje profesor.
        /// </summary>
        public static string ShowStudentsForProfessor {
            get {
                return ResourceManager.GetString("ShowStudentsForProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifra predmeta*:.
        /// </summary>
        public static string Sifra_ {
            get {
                return ResourceManager.GetString("Sifra*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studentska služba.
        /// </summary>
        public static string Student_union {
            get {
                return ResourceManager.GetString("Student union", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studenti koji su položili jedan a nisu drugi predmet:.
        /// </summary>
        public static string Studenti_koji_su_položili_jedan_a_nisu_drugi_predmet {
            get {
                return ResourceManager.GetString("Studenti koji su položili jedan a nisu drugi predmet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studenti kojima profesor predaje:.
        /// </summary>
        public static string Studenti_kojima_profesor_predaje_ {
            get {
                return ResourceManager.GetString("Studenti kojima profesor predaje:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeks studenta:.
        /// </summary>
        public static string StudentIndex {
            get {
                return ResourceManager.GetString("StudentIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studenti.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studenti na predmetu.
        /// </summary>
        public static string Students_on_course {
            get {
                return ResourceManager.GetString("Students on course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studenti na predmetu:.
        /// </summary>
        public static string Students_on_course_ {
            get {
                return ResourceManager.GetString("Students on course:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studentska služba.
        /// </summary>
        public static string Studentska_služba {
            get {
                return ResourceManager.GetString("Studentska služba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime:.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svi predmeti svih profesora sa izbarane katedre:.
        /// </summary>
        public static string Svi_predmeti_svih_profesora_sa_izbarane_katedre_ {
            get {
                return ResourceManager.GetString("Svi predmeti svih profesora sa izbarane katedre:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polaganje.
        /// </summary>
        public static string Take_exam {
            get {
                return ResourceManager.GetString("Take exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvanje:.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukloni predmet.
        /// </summary>
        public static string Ukloni_predmet {
            get {
                return ResourceManager.GetString("Ukloni predmet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos ocene.
        /// </summary>
        public static string Unos_ocene {
            get {
                return ResourceManager.GetString("Unos ocene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.0.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina:.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina studija:.
        /// </summary>
        public static string Year_of_study {
            get {
                return ResourceManager.GetString("Year of study", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zimski.
        /// </summary>
        public static string Zimski {
            get {
                return ResourceManager.GetString("Zimski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvanje:.
        /// </summary>
        public static string Zvanje {
            get {
                return ResourceManager.GetString("Zvanje", resourceCulture);
            }
        }
    }
}
